name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 拉代码
    - name: Checkout
      uses: actions/checkout@v4

    # 安装基础依赖
    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential clang git wget xz-utils

    # 安装 Theos + SDK + Toolchain（关键三件套）
    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        git clone https://github.com/theos/sdks.git $HOME/theos/sdks
        git clone https://github.com/theos/toolchain.git $HOME/theos/toolchain

    # 编译
    - name: Build Package
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/toolchain/linux/iphone/bin:$PATH
        make clean package FINALPACKAGE=1

    # 上传 deb
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb
        path: packages/*.deb
